# День 00 – Сбор данных

Добро пожаловать в Jupyter Notebook! Это тот инструмент, в котором дата сайентисты проводят больше всего времени, работая с данными при помощи кода на Python. Здесь очень удобно работать в интерактивном режиме, запуская отдельные ячейки, а не весь код сразу и полностью. Тут же можно делать и отчеты, поскольку помимо кода, здесь удобно строить графики и писать текст.

Мы понимаем, что вы не программисты и скорее всего не планируете ими стать, поэтому насколько это возможно мы будем сопровождать такие ноутбуки комментариями и полезными командами, которые могут вам пригодиться для решения задачи. Но естественно здесь будет не всё: что-то вам придется поискать самостоятельно в интернете. Такова уж методология Школы 21, и она приносит свои плоды.

## 0. Импорт библиотек

Библиотека – это по сути набор полезных функций и методов, которые написали одни программисты, а другие программисты могут уже не писать их с нуля, а пользоваться готовыми. Например, вы хотите посчитать среднее арифметическое значение по ряду. Вы можете самостоятельно написать код, который посчитает сумму по ряду и поделит на количество элементов в ряду, а можете импортировать библиотеку, где уже есть эта функция и воспользоваться ею. Это сэкономит вам время, силы, и код будет менее объемным.

Ниже мы импортируем широко используемую библиотеку Pandas. В ней есть много полезных функций для работы с табличными данными. Почти Excel, только взаимодействие с ним через код на Python. Мы будем пользоваться этой библиотекой в течение всего курса.

In [ ]:
import pandas as pd #мы будем часто пользоваться методами этой библиотеки, поэтому введем для нее сокращенное название – pd

## 1. Загрузка данных

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

In [ ]:
df1 = pd.read_csv('/content/drive/MyDrive/School21/day00/part_01.csv') #указываем путь к файлу
df1.head() #посмотрим несколько первых строк получившегося датафрейма

,ID,AMOUNT_RUB_ATM_PRC,AMOUNT_RUB_CLO_PRC,AMOUNT_RUB_NAS_PRC,AMOUNT_RUB_SUP_PRC,CNT_TRAN_ATM_TENDENCY1M,CNT_TRAN_ATM_TENDENCY3M,CNT_TRAN_AUT_TENDENCY1M,CNT_TRAN_AUT_TENDENCY3M,CNT_TRAN_CLO_TENDENCY1M,...,SUM_TRAN_CLO_TENDENCY3M,SUM_TRAN_MED_TENDENCY1M,SUM_TRAN_MED_TENDENCY3M,SUM_TRAN_SUP_TENDENCY1M,SUM_TRAN_SUP_TENDENCY3M,TRANS_AMOUNT_TENDENCY3M,TRANS_CNT_TENDENCY3M,TRANS_COUNT_ATM_PRC,TRANS_COUNT_NAS_PRC,TRANS_COUNT_SUP_PRC
0,199360,1.000000,0.000000,0.0000,0.000000,0.250000,0.750000,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,0.744186,0.750000,1.000000,0.000000,0.000000
1,285903,0.548968,0.006725,0.0000,0.102824,0.025000,0.650000,NaN,0.666667,NaN,...,NaN,0.023043,0.365189,NaN,0.368032,0.486163,0.511628,0.232558,0.000000,0.052326
2,259249,0.060149,0.000000,0.0000,0.615370,NaN,NaN,1.0,1.000000,NaN,...,NaN,NaN,NaN,NaN,1.000000,0.939851,0.875000,0.125000,0.000000,0.125000
3,447959,0.096392,0.363477,0.0093,0.136140,0.166667,0.500000,NaN,NaN,0.090909,...,0.452527,NaN,0.130446,0.116332,0.351140,0.435642,0.418803,0.051282,0.008547,0.179487
4,196498,0.881967,0.050398,0.0000,0.062595,0.142857,0.142857,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,0.105836,0.153846,0.538462,0.000000,0.307692

Если всё получилось, то вы увидите небольшой кусок таблицы: шапку, первые пять строчек и часть столбцов (несколько первых и несколько последних).

## 2. Полезные команды

Ниже мы покажем несколько полезных команд, которые вам могут пригодиться для выполнения сегодняшнего задания.

1. Узнать **названия полей** в датафрейме.

In [ ]:
df1.columns

Index(['ID', 'AMOUNT_RUB_ATM_PRC', 'AMOUNT_RUB_CLO_PRC', 'AMOUNT_RUB_NAS_PRC',
       'AMOUNT_RUB_SUP_PRC', 'CNT_TRAN_ATM_TENDENCY1M',
       'CNT_TRAN_ATM_TENDENCY3M', 'CNT_TRAN_AUT_TENDENCY1M',
       'CNT_TRAN_AUT_TENDENCY3M', 'CNT_TRAN_CLO_TENDENCY1M',
       'CNT_TRAN_CLO_TENDENCY3M', 'CNT_TRAN_MED_TENDENCY1M',
       'CNT_TRAN_MED_TENDENCY3M', 'CNT_TRAN_SUP_TENDENCY1M',
       'CNT_TRAN_SUP_TENDENCY3M', 'SUM_TRAN_ATM_TENDENCY1M',
       'SUM_TRAN_ATM_TENDENCY3M', 'SUM_TRAN_AUT_TENDENCY1M',
       'SUM_TRAN_AUT_TENDENCY3M', 'SUM_TRAN_CLO_TENDENCY1M',
       'SUM_TRAN_CLO_TENDENCY3M', 'SUM_TRAN_MED_TENDENCY1M',
       'SUM_TRAN_MED_TENDENCY3M', 'SUM_TRAN_SUP_TENDENCY1M',
       'SUM_TRAN_SUP_TENDENCY3M', 'TRANS_AMOUNT_TENDENCY3M',
       'TRANS_CNT_TENDENCY3M', 'TRANS_COUNT_ATM_PRC', 'TRANS_COUNT_NAS_PRC',
       'TRANS_COUNT_SUP_PRC'],
      dtype='object')

2. Присоединить датафрейм **снизу**:

In [ ]:
new_df = pd.concat([df1, df1])
new_df

,ID,AMOUNT_RUB_ATM_PRC,AMOUNT_RUB_CLO_PRC,AMOUNT_RUB_NAS_PRC,AMOUNT_RUB_SUP_PRC,CNT_TRAN_ATM_TENDENCY1M,CNT_TRAN_ATM_TENDENCY3M,CNT_TRAN_AUT_TENDENCY1M,CNT_TRAN_AUT_TENDENCY3M,CNT_TRAN_CLO_TENDENCY1M,...,SUM_TRAN_CLO_TENDENCY3M,SUM_TRAN_MED_TENDENCY1M,SUM_TRAN_MED_TENDENCY3M,SUM_TRAN_SUP_TENDENCY1M,SUM_TRAN_SUP_TENDENCY3M,TRANS_AMOUNT_TENDENCY3M,TRANS_CNT_TENDENCY3M,TRANS_COUNT_ATM_PRC,TRANS_COUNT_NAS_PRC,TRANS_COUNT_SUP_PRC
0,199360,1.000000,0.000000,0.000000,0.000000,0.250000,0.750000,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,0.744186,0.750000,1.000000,0.000000,0.000000
1,285903,0.548968,0.006725,0.000000,0.102824,0.025000,0.650000,NaN,0.666667,NaN,...,NaN,0.023043,0.365189,NaN,0.368032,0.486163,0.511628,0.232558,0.000000,0.052326
2,259249,0.060149,0.000000,0.000000,0.615370,NaN,NaN,1.0,1.000000,NaN,...,NaN,NaN,NaN,NaN,1.000000,0.939851,0.875000,0.125000,0.000000,0.125000
3,447959,0.096392,0.363477,0.009300,0.136140,0.166667,0.500000,NaN,NaN,0.090909,...,0.452527,NaN,0.130446,0.116332,0.351140,0.435642,0.418803,0.051282,0.008547,0.179487
4,196498,0.881967,0.050398,0.000000,0.062595,0.142857,0.142857,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,0.105836,0.153846,0.538462,0.000000,0.307692
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
177590,496698,1.000000,0.000000,0.000000,0.000000,0.400000,0.800000,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,0.983819,0.800000,1.000000,0.000000,0.000000
177591,383782,0.740151,0.126350,0.000000,0.026732,0.406250,1.000000,1.0,1.000000,0.545455,...,1.000000,NaN,1.000000,0.345832,1.000000,1.000000,1.000000,0.405063,0.000000,0.189873
177592,175289,0.999661,0.000000,0.000000,0.000000,0.200000,0.300000,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,0.400542,0.272727,0.909091,0.000000,0.000000
177593,467697,0.852134,0.000000,0.000000,0.068945,0.281250,0.875000,1.0,1.000000,NaN,...,NaN,0.322581,0.881720,0.232570,0.859741,0.784559,0.863248,0.273504,0.000000,0.444444
177594,548533,0.000000,0.000000,0.725952,0.000000,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,0.410905,0.377193,0.000000,0.763158,0.000000

3. Присоединить датафрейм **справа**:

In [ ]:
df1.merge(df1, left_on='ID', right_on='ID') # выбираем ID в качестве ключа, по которому датафреймы будут объединяться

,ID,AMOUNT_RUB_ATM_PRC_x,AMOUNT_RUB_CLO_PRC_x,AMOUNT_RUB_NAS_PRC_x,AMOUNT_RUB_SUP_PRC_x,CNT_TRAN_ATM_TENDENCY1M_x,CNT_TRAN_ATM_TENDENCY3M_x,CNT_TRAN_AUT_TENDENCY1M_x,CNT_TRAN_AUT_TENDENCY3M_x,CNT_TRAN_CLO_TENDENCY1M_x,...,SUM_TRAN_CLO_TENDENCY3M_y,SUM_TRAN_MED_TENDENCY1M_y,SUM_TRAN_MED_TENDENCY3M_y,SUM_TRAN_SUP_TENDENCY1M_y,SUM_TRAN_SUP_TENDENCY3M_y,TRANS_AMOUNT_TENDENCY3M_y,TRANS_CNT_TENDENCY3M_y,TRANS_COUNT_ATM_PRC_y,TRANS_COUNT_NAS_PRC_y,TRANS_COUNT_SUP_PRC_y
0,199360,1.000000,0.000000,0.000000,0.000000,0.250000,0.750000,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,0.744186,0.750000,1.000000,0.000000,0.000000
1,285903,0.548968,0.006725,0.000000,0.102824,0.025000,0.650000,NaN,0.666667,NaN,...,NaN,0.023043,0.365189,NaN,0.368032,0.486163,0.511628,0.232558,0.000000,0.052326
2,259249,0.060149,0.000000,0.000000,0.615370,NaN,NaN,1.0,1.000000,NaN,...,NaN,NaN,NaN,NaN,1.000000,0.939851,0.875000,0.125000,0.000000,0.125000
3,447959,0.096392,0.363477,0.009300,0.136140,0.166667,0.500000,NaN,NaN,0.090909,...,0.452527,NaN,0.130446,0.116332,0.351140,0.435642,0.418803,0.051282,0.008547,0.179487
4,196498,0.881967,0.050398,0.000000,0.062595,0.142857,0.142857,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,0.105836,0.153846,0.538462,0.000000,0.307692
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
177590,496698,1.000000,0.000000,0.000000,0.000000,0.400000,0.800000,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,0.983819,0.800000,1.000000,0.000000,0.000000
177591,383782,0.740151,0.126350,0.000000,0.026732,0.406250,1.000000,1.0,1.000000,0.545455,...,1.000000,NaN,1.000000,0.345832,1.000000,1.000000,1.000000,0.405063,0.000000,0.189873
177592,175289,0.999661,0.000000,0.000000,0.000000,0.200000,0.300000,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,0.400542,0.272727,0.909091,0.000000,0.000000
177593,467697,0.852134,0.000000,0.000000,0.068945,0.281250,0.875000,1.0,1.000000,NaN,...,NaN,0.322581,0.881720,0.232570,0.859741,0.784559,0.863248,0.273504,0.000000,0.444444
177594,548533,0.000000,0.000000,0.725952,0.000000,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,0.410905,0.377193,0.000000,0.763158,0.000000

Если вам не хватает команд, представленных в этом ноутбуке, то вы можете **самостоятельно воспользоваться поиском в Google**.

    "pandas how to save a csv-file with header"

## 3. Самостоятельная часть

Ниже вам нужно самим собрать целиком датасет из разрозненных кусков.